### ISSUE TITLE
Syllable Feature Diacritic after the 3rd syllable applies incorrectly

### ISSUE THREAD

**Issue by nicodoggie** [def-gthill/lexurgy-app#2]
Diacritics applied to any syllable after the 3rd syllable outputs with the diacrtic applied to the 3rd syllable all the time.
I tried to make this minimal case:
```
Feature (syllable) +stress
Diacritic ˈ (before) [+stress] 


Syllables:
  {p,t,k}? {a,i,u}
```
With input
```
ˈpapapa
tiˈtititi
kukukuˈkuku
```
[Share Link](www.lexurgy.com/sc?changes=RmVhdHVyZSAoc3lsbGFibGUpICtzdHJlc3MKRGlhY3JpdGljIMuIIChiZWZvcmUpIFsrc3RyZXNzXSAKCgpTeWxsYWJsZXM6CiAge3AsdCxrfT8ge2EsaSx1fQo&input=y4hwYXBhcGEKdGnLiHRpdGl0aQprdWt1a3XLiGt1a3U
)

| Input Word	 | Output Word |
| --- | --- |
|ˈpapapa|	ˈpa.pa.pa|
|tiˈtititi|	ti.ˈti.ti.ti|
|kukukuˈkuku|	ku.ku.ˈku.ku.ku|
|tatatataˈta|	ta.ta.ˈta.ta.ta|

First two examples, the diacritic is applied correctly, as long as they're applied in the first 3 syllables. When the diacritics are placed after that, they're always applied to position 3.

**Comment by def-gthill** [comment]
Moved to the main Lexurgy repo, as it isn't an issue with the UI.
